[workspace]
resolver = "2"

members = ["api", "cli", "examples", "lib", "macro", "parser"]

[workspace.package]
version = "0.17.2"

[workspace.dependencies]
kinetics-api = { path = "api", version = "0.17.2" }
kinetics-lib = { path = "lib", version = "0.17.2" }
kinetics-macro = { path = "macro", version = "0.17.2" }
kinetics-parser = { path = "parser", version = "0.17.2" }

# Do not upgrade as TOML parsing fails
toml = "=0.8.23"

tokio = "1.51.1"
