[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-sdk-cloudformation = "1.66.0"
lambda_http = "0.14.0"
uuid = { version = "1.13.1", features = ["v4"]}
lambda_runtime = "0.13.0"
kinetics-macro = { path = "../macro" }
aws-config = "1.5.16"
aws-sdk-s3 = "1.76.0"
eyre = "0.6.12"
serde_json = "1.0.138"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.20"
zip = "2.2.2"
aws-sdk-ssm = "1.65.0"
regex = "1.11.1"
aws-sdk-dynamodb = "1.65.0"
serde-email = "3.1.0"
chrono = "0.4.39"
rand = "0.9.0"
reqwest = { version = "0.12.12", default-features = false, features = ["rustls-tls", "json"] }
sha256 = "1.5.0"
magic-crypt = "4.0.1"

[package.metadata.kinetics.kvdb.kinetics]
name = "kinetics"
