[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = "0.14.0"
lambda_runtime = "0.13.0"
skymacro = { path = "../macro" }
aws-config = "1.5.15"
aws-sdk-s3 = "1.71.0"
eyre = "0.6.12"
serde_json = "1.0.137"

[package.metadata.sky.stack]
name = "kinetics-backend"
