[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-sdk-cloudformation = "1.62.0"
lambda_http = "0.14.0"
uuid = { version = "1.12.1", features = ["v4"]}
lambda_runtime = "0.13.0"
skymacro = { path = "../macro" }
aws-config = "1.5.15"
aws-sdk-s3 = "1.71.0"
eyre = "0.6.12"
serde_json = "1.0.137"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.19"
zip = "2.2.2"
aws-sdk-ssm = "1.62.1"
regex = "1.11.1"
aws-sdk-dynamodb = "1.62.0"
serde-email = "3.1.0"
chrono = "0.4.39"
rand = "0.8.5"
reqwest = { version = "0.12.12", default-features = false, features = ["rustls-tls", "json"] }
sha256 = "1.5.0"

[package.metadata.sky.stack]
name = "kinetics-backend"

[package.metadata.sky.kvdb.kinetics]
name = "kinetics"
