[package]
name = "kinetics-macro"
version = "0.16.0"
edition = "2021"
description = "A set of macros used in Kinetics project."
repository = "https://github.com/ottofeller/kinetics"
license = "Apache-2.0 OR MIT"
keywords = ["kinetics", "macro", "rust"]
categories = ["parsing"]

[lib]
proc-macro = true

[dependencies]
kinetics-parser = { path = "../parser", version = "0.16.0" }
syn = "2.0.117"
