[package]
name = "kinetics-parser"
version = "0.15.8"
edition = "2021"
description = "A parser used for Kinetics project."
repository = "https://github.com/ottofeller/kinetics"
license = "Apache-2.0 OR MIT"
keywords = ["kinetics", "macro", "parser", "rust"]
categories = ["parsing"]

[dependencies]
color-eyre = "0.6.5"
http = "1.4"
serde = { version = "1.0.228", features = ["derive"] }
syn = { version = "2.0", features = ["full", "visit"] }
walkdir = "2.5.0"
