#![feature(once_cell_try)]
pub mod build;
pub mod cli;
pub mod client;
pub mod config;
pub mod crat;
pub mod credentials;
pub mod deploy;
pub mod destroy;
pub mod error;
pub mod function;
pub mod init;
pub mod invoke;
pub mod list;
pub mod logger;
pub mod login;
pub mod logout;
pub mod logs;
pub mod secret;
